name: "Lint Pull Request Title"

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  pull-request-title-lint:
    name: Lint Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - name: Lint Pull Request Title
        id: lint_pr_title
        # amannn/action-semantic-pull-request@v6.1.1
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sticky Pull Request Comment
        # marocchino/sticky-pull-request-comment@v2.9.4
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: Pull request titles must follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/), please update your pull request title.
      - name: Delete Sticky Pull Request Comment
        # marocchino/sticky-pull-request-comment@v2.9.4
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        with:
          header: pr-title-lint-error
          delete: true
